version: "3"

services:
  db:
    image: postgres:9.6
    ports:
      - "5433:5432"
    logging:
      driver: "none"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    build: .
    command: "bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
      - gems:/bundle
    ports:
      - "0.0.0.0:3000:3000"
    links:
      - db
    depends_on:
      - db

volumes:
  gems:
